[workspace]
members = [
    "runtime",
    "glue",
    "natives-gen",

    "bindings",
    "bindings/core",
    "bindings/client",
    "bindings/server",
    "bindings/shared",

    # test
    "standalone",

    # examples
    "examples/basic-client",
    "examples/basic-server"
]
