[workspace]
members = [
    "runtime",
    "glue",
    "bindings",
    "bindings/core",
    "bindings/client",
    "bindings/server",

    # test
    "standalone",

    # examples
    "examples/basic",
]
