[package]
name = "standalone"
version = "0.1.0"
authors = ["ZOTTCE <zottce@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "0.15.4"
rmpv = "0.4.7"
serde_bytes = "0.11"
