[package]
name = "natives-gen"
version = "0.1.0"
authors = ["ZOTTCE <zottce@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"
full_moon = "0.11.0"
joaat = "0.1.0"
itertools = "0.10.0"
convert_case = "0.4.0"
