[package]
name = "fivem"
version = "0.1.0"
authors = ["ZOTTCE <zottce@gmail.com>"]
edition = "2018"

[features]
default = ["full"]
types = []
client = []
server = []
full = ["types", "futures", "serde"]

[dependencies]
rmp-serde = "0.15.4"
futures = { version = "0.3.14", features = ["executor"], optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
