[package]
name = "fivem"
version = "0.1.0"
authors = ["ZOTTCE <zottce@gmail.com>"]
edition = "2018"

[features]
default = []
server = ["fivem-server"]
client = ["fivem-client"]

[dependencies]
fivem-core = { path = "core/" }
fivem-client = { path = "client/", optional = true }
fivem-server = { path = "server/", optional = true }
